apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-secrets
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- $path := printf "config/%s/sealed-secrets-values.yaml" .Values.environment }} {{ range .Files.Lines $path }}
    {{ . }}{{ end }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: demo-secrets
      namespace: {{ .Values.namespace }}